/**
 * Structured error taxonomy for The Last Exam.
 *
 * Error categories:
 * - VALIDATION: Bad input (malformed requests, schema violations, constraint failures)
 * - TIMEOUT: Phase/run deadline expired
 * - SANDBOX: Execution limit violations (memory, CPU, disk)
 * - NETWORK: Connectivity failures (API calls, WebSocket, runner callbacks)
 * - INTERNAL: Server bugs, unexpected state, invariant violations
 */

export const ErrorCategory = {
  VALIDATION: 'VALIDATION',
  TIMEOUT: 'TIMEOUT',
  SANDBOX: 'SANDBOX',
  NETWORK: 'NETWORK',
  INTERNAL: 'INTERNAL',
} as const;

export type ErrorCategory = (typeof ErrorCategory)[keyof typeof ErrorCategory];

/**
 * Fine-grained error codes within each category.
 * Format: CATEGORY_SPECIFIC_ERROR
 */
export const ErrorCode = {
  // VALIDATION errors
  VALIDATION_SCHEMA: 'VALIDATION_SCHEMA',
  VALIDATION_BID_OUT_OF_RANGE: 'VALIDATION_BID_OUT_OF_RANGE',
  VALIDATION_BID_PHASE_CLOSED: 'VALIDATION_BID_PHASE_CLOSED',
  VALIDATION_EQUIP_INVALID_TOOL: 'VALIDATION_EQUIP_INVALID_TOOL',
  VALIDATION_EQUIP_CONSTRAINT: 'VALIDATION_EQUIP_CONSTRAINT',
  VALIDATION_EQUIP_PHASE_CLOSED: 'VALIDATION_EQUIP_PHASE_CLOSED',
  VALIDATION_MATCH_NOT_FOUND: 'VALIDATION_MATCH_NOT_FOUND',
  VALIDATION_INVALID_TRANSITION: 'VALIDATION_INVALID_TRANSITION',
  VALIDATION_CONTENT_SCHEMA: 'VALIDATION_CONTENT_SCHEMA',
  VALIDATION_DUPLICATE_SUBMISSION: 'VALIDATION_DUPLICATE_SUBMISSION',

  // TIMEOUT errors
  TIMEOUT_PHASE_DEADLINE: 'TIMEOUT_PHASE_DEADLINE',
  TIMEOUT_RUN_EXECUTION: 'TIMEOUT_RUN_EXECUTION',
  TIMEOUT_COMMENTARY_GENERATION: 'TIMEOUT_COMMENTARY_GENERATION',
  TIMEOUT_LLM_CALL: 'TIMEOUT_LLM_CALL',
  TIMEOUT_RUNNER_CALLBACK: 'TIMEOUT_RUNNER_CALLBACK',

  // SANDBOX errors
  SANDBOX_MEMORY_LIMIT: 'SANDBOX_MEMORY_LIMIT',
  SANDBOX_CPU_LIMIT: 'SANDBOX_CPU_LIMIT',
  SANDBOX_DISK_LIMIT: 'SANDBOX_DISK_LIMIT',
  SANDBOX_NETWORK_BLOCKED: 'SANDBOX_NETWORK_BLOCKED',
  SANDBOX_PROCESS_KILLED: 'SANDBOX_PROCESS_KILLED',
  SANDBOX_SYNTAX_ERROR: 'SANDBOX_SYNTAX_ERROR',
  SANDBOX_RUNTIME_ERROR: 'SANDBOX_RUNTIME_ERROR',

  // NETWORK errors
  NETWORK_WS_DISCONNECTED: 'NETWORK_WS_DISCONNECTED',
  NETWORK_RUNNER_UNREACHABLE: 'NETWORK_RUNNER_UNREACHABLE',
  NETWORK_LLM_API_FAILURE: 'NETWORK_LLM_API_FAILURE',
  NETWORK_GEMINI_TTS_FAILURE: 'NETWORK_GEMINI_TTS_FAILURE',
  NETWORK_CALLBACK_FAILED: 'NETWORK_CALLBACK_FAILED',

  // INTERNAL errors
  INTERNAL_FSM_INVARIANT: 'INTERNAL_FSM_INVARIANT',
  INTERNAL_SCORING_ERROR: 'INTERNAL_SCORING_ERROR',
  INTERNAL_PERSISTENCE_ERROR: 'INTERNAL_PERSISTENCE_ERROR',
  INTERNAL_UNEXPECTED: 'INTERNAL_UNEXPECTED',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

/** Map each error code to its category */
export const ERROR_CODE_CATEGORY: Record<ErrorCode, ErrorCategory> = {
  VALIDATION_SCHEMA: ErrorCategory.VALIDATION,
  VALIDATION_BID_OUT_OF_RANGE: ErrorCategory.VALIDATION,
  VALIDATION_BID_PHASE_CLOSED: ErrorCategory.VALIDATION,
  VALIDATION_EQUIP_INVALID_TOOL: ErrorCategory.VALIDATION,
  VALIDATION_EQUIP_CONSTRAINT: ErrorCategory.VALIDATION,
  VALIDATION_EQUIP_PHASE_CLOSED: ErrorCategory.VALIDATION,
  VALIDATION_MATCH_NOT_FOUND: ErrorCategory.VALIDATION,
  VALIDATION_INVALID_TRANSITION: ErrorCategory.VALIDATION,
  VALIDATION_CONTENT_SCHEMA: ErrorCategory.VALIDATION,
  VALIDATION_DUPLICATE_SUBMISSION: ErrorCategory.VALIDATION,
  TIMEOUT_PHASE_DEADLINE: ErrorCategory.TIMEOUT,
  TIMEOUT_RUN_EXECUTION: ErrorCategory.TIMEOUT,
  TIMEOUT_COMMENTARY_GENERATION: ErrorCategory.TIMEOUT,
  TIMEOUT_LLM_CALL: ErrorCategory.TIMEOUT,
  TIMEOUT_RUNNER_CALLBACK: ErrorCategory.TIMEOUT,
  SANDBOX_MEMORY_LIMIT: ErrorCategory.SANDBOX,
  SANDBOX_CPU_LIMIT: ErrorCategory.SANDBOX,
  SANDBOX_DISK_LIMIT: ErrorCategory.SANDBOX,
  SANDBOX_NETWORK_BLOCKED: ErrorCategory.SANDBOX,
  SANDBOX_PROCESS_KILLED: ErrorCategory.SANDBOX,
  SANDBOX_SYNTAX_ERROR: ErrorCategory.SANDBOX,
  SANDBOX_RUNTIME_ERROR: ErrorCategory.SANDBOX,
  NETWORK_WS_DISCONNECTED: ErrorCategory.NETWORK,
  NETWORK_RUNNER_UNREACHABLE: ErrorCategory.NETWORK,
  NETWORK_LLM_API_FAILURE: ErrorCategory.NETWORK,
  NETWORK_GEMINI_TTS_FAILURE: ErrorCategory.NETWORK,
  NETWORK_CALLBACK_FAILED: ErrorCategory.NETWORK,
  INTERNAL_FSM_INVARIANT: ErrorCategory.INTERNAL,
  INTERNAL_SCORING_ERROR: ErrorCategory.INTERNAL,
  INTERNAL_PERSISTENCE_ERROR: ErrorCategory.INTERNAL,
  INTERNAL_UNEXPECTED: ErrorCategory.INTERNAL,
};

/** Get the category for a given error code */
export function getErrorCategory(code: ErrorCode): ErrorCategory {
  return ERROR_CODE_CATEGORY[code];
}
